<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="4" failed="0" ignored="0" total="4" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Facilitating Successful Immunization Workflow Change iDetail Migration is not being initiated and proceeding with Operational Analytical Suite]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="2120741" started-at="2020-02-17T09:37:51Z" finished-at="2020-02-17T10:13:12Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="2120741" started-at="2020-02-17T09:37:51Z" finished-at="2020-02-17T10:13:12Z">
      <class name="src.com.salesforce.SingleRun.MVRTest_SingleRun_ClmRteDevEnv">
        <test-method status="PASS" signature="migration()[pri:0, instance:src.com.salesforce.SingleRun.MVRTest_SingleRun_ClmRteDevEnv@1c27493]" name="migration" is-config="true" duration-ms="2096883" started-at="2020-02-17T15:07:51Z" finished-at="2020-02-17T15:42:48Z">
          <reporter-output>
            <line>
              <![CDATA[Facilitating Successful Immunization Workflow Change iDetail Migration is not being initiated and proceeding with Operational Analytical Suite]]>
            </line>
          </reporter-output>
        </test-method> <!-- migration -->
        <test-method status="SKIP" signature="login()[pri:0, instance:src.com.salesforce.SingleRun.MVRTest_SingleRun_ClmRteDevEnv@1c27493]" name="login" duration-ms="21620" started-at="2020-02-17T15:42:48Z" finished-at="2020-02-17T15:43:10Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Please close the MVR Output Report/Screenshots file]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Please close the MVR Output Report/Screenshots file
	at src.com.salesforce.SingleRun.MVRTest_SingleRun_ClmRteDevEnv.login(MVRTest_SingleRun_ClmRteDevEnv.java:294)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="SKIP" signature="clmPresentationMetadataReport()[pri:0, instance:src.com.salesforce.SingleRun.MVRTest_SingleRun_ClmRteDevEnv@1c27493]" name="clmPresentationMetadataReport" duration-ms="0" started-at="2020-02-17T15:43:10Z" depends-on-methods="src.com.salesforce.SingleRun.MVRTest_SingleRun_ClmRteDevEnv.login" finished-at="2020-02-17T15:43:10Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MVRTest_SingleRun_ClmRteDevEnv.clmPresentationMetadataReport()[pri:0, instance:src.com.salesforce.SingleRun.MVRTest_SingleRun_ClmRteDevEnv@1c27493] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MVRTest_SingleRun_ClmRteDevEnv.clmPresentationMetadataReport()[pri:0, instance:src.com.salesforce.SingleRun.MVRTest_SingleRun_ClmRteDevEnv@1c27493] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1084)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clmPresentationMetadataReport -->
        <test-method status="SKIP" signature="keyMessageMetadataReport()[pri:0, instance:src.com.salesforce.SingleRun.MVRTest_SingleRun_ClmRteDevEnv@1c27493]" name="keyMessageMetadataReport" duration-ms="0" started-at="2020-02-17T15:43:10Z" depends-on-methods="src.com.salesforce.SingleRun.MVRTest_SingleRun_ClmRteDevEnv.clmPresentationMetadataReport" finished-at="2020-02-17T15:43:10Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MVRTest_SingleRun_ClmRteDevEnv.keyMessageMetadataReport()[pri:0, instance:src.com.salesforce.SingleRun.MVRTest_SingleRun_ClmRteDevEnv@1c27493] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MVRTest_SingleRun_ClmRteDevEnv.keyMessageMetadataReport()[pri:0, instance:src.com.salesforce.SingleRun.MVRTest_SingleRun_ClmRteDevEnv@1c27493] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1084)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- keyMessageMetadataReport -->
        <test-method status="SKIP" signature="sendEmailTest()[pri:0, instance:src.com.salesforce.SingleRun.MVRTest_SingleRun_ClmRteDevEnv@1c27493]" name="sendEmailTest" duration-ms="0" started-at="2020-02-17T15:43:10Z" depends-on-methods="src.com.salesforce.SingleRun.MVRTest_SingleRun_ClmRteDevEnv.keyMessageMetadataReport" finished-at="2020-02-17T15:43:10Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method MVRTest_SingleRun_ClmRteDevEnv.sendEmailTest()[pri:0, instance:src.com.salesforce.SingleRun.MVRTest_SingleRun_ClmRteDevEnv@1c27493] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method MVRTest_SingleRun_ClmRteDevEnv.sendEmailTest()[pri:0, instance:src.com.salesforce.SingleRun.MVRTest_SingleRun_ClmRteDevEnv@1c27493] depends on not successfully finished methods
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1084)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sendEmailTest -->
        <test-method status="FAIL" signature="logout()[pri:0, instance:src.com.salesforce.SingleRun.MVRTest_SingleRun_ClmRteDevEnv@1c27493]" name="logout" is-config="true" duration-ms="1338" started-at="2020-02-17T15:43:10Z" finished-at="2020-02-17T15:43:12Z">
          <exception class="java.lang.ExceptionInInitializerError">
            <full-stacktrace>
              <![CDATA[java.lang.ExceptionInInitializerError
	at src.com.salesforce.SingleRun.MVRTest_SingleRun_ClmRteDevEnv.logout(MVRTest_SingleRun_ClmRteDevEnv.java:1092)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:146)
	at org.testng.TestRunner.afterRun(TestRunner.java:958)
	at org.testng.TestRunner.run(TestRunner.java:606)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html
	at com.google.common.base.Preconditions.checkState(Preconditions.java:847)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:125)
	at org.openqa.selenium.chrome.ChromeDriverService.access$000(ChromeDriverService.java:35)
	at org.openqa.selenium.chrome.ChromeDriverService$Builder.findDefaultExecutable(ChromeDriverService.java:156)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:346)
	at org.openqa.selenium.chrome.ChromeDriverService.createDefaultService(ChromeDriverService.java:91)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:123)
	at com.salesforce.genericLib.Driver.<clinit>(Driver.java:13)
	... 24 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ExceptionInInitializerError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
      </class> <!-- src.com.salesforce.SingleRun.MVRTest_SingleRun_ClmRteDevEnv -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
